import type { Metadata } from "next";
import { Lexend as Font } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const font = Font({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SamyOS Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />

        <main className="max-w-4xl mx-auto px-8 lg:px-0 py-16 text-lg space-y-16">
          {children}
        </main>
      </body>
    </html>
  );
}
